// <auto-generated />
namespace FortyLife.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddRulings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRulings));
        
        string IMigrationMetadata.Id
        {
            get { return "201902162051269_AddRulings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
